name: TSSEndExpansion
version: '0.1'
main: org.esoteric.tss.minecraft.plugins.end.expansion.TSSEndExpansionPlugin
api-version: '1.21'
dependencies:
  server:
    TSSCore:
      required: true
      load: BEFORE

author: Esoteric Organisation
contributors:
  - Esoteric Enderman
description: A Minecraft plugin designed to make The Slimy Swamp's end much more challenging and difficult.
